Repository Interacao-Humano-Computador/2022.1-Faculdade-de-Arquitetura-e-Urbanismo, pull requests merged in 2022-07, with the labels that each got.

#1 Processo de design
  .github/workflows/deploy.yml
  docs/assets/ciclo_mayhew.png
  docs/planejamento/cronograma-de-atividades.md
  docs/planejamento/escolha-do-site.md
  docs/planejamento/metodologia-e-processos.md
  docs/planejamento/processo-de-design.md
  mkdocs.yml
Labels: enhancement

#11 add deploy on push to development branch
  .github/workflows/deploy.yml
Labels: enhancement

#17 Aspectos éticos
  docs/analise-de-requisitos/aspectos-eticos.md
  docs/assets/termo-de-consentimento.pdf
  mkdocs.yml
Labels: entrega2

#22 Escolha do site e sites avaliados
  docs/assets/img_decide.png
  docs/assets/logo_fau_homepage.png
  docs/assets/tabela_heuristica.png
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoCaio.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoLeticia.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoMateusF.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoMatheusC.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoThalisson.pdf
  docs/planejamento/analiseSites/escolha-do-site.md
  docs/planejamento/analiseSites/site-escolhido.md
  mkdocs.yml
Labels: entrega2

#25 Development
  README.md
  docs/Perfil-de-usuario.md
  docs/analise-de-requisitos/aspectos-eticos.md
  docs/analise-de-requisitos/personas.md
  docs/analise-de-tarefas.md
  docs/apresentacoes.md
  docs/apresentacoes/apresentacao1.md
  docs/assets/hta-consulta-de-fluxograma.png
  docs/assets/img_decide.png
  docs/assets/logo_fau_homepage.png
  docs/assets/persona1.jpg
  docs/assets/persona2.jpg
  docs/assets/persona3.jpg
  docs/assets/tabela-figura2.png
  docs/assets/tabela-hta.png
  docs/assets/tabela_heuristica.png
  docs/assets/termo-de-consentimento.pdf
  docs/index.md
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoCaio.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoLeticia.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoMateusF.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoMatheusC.pdf
  docs/planejamento/analiseSites/avaliacoesIndividuais/AvaliacaoThalisson.pdf
  docs/planejamento/analiseSites/escolha-do-site.md
  docs/planejamento/analiseSites/site-escolhido.md
  docs/planejamento/cronograma-de-atividades.md
  docs/planejamento/metodologia-e-processos.md
  docs/planejamento/processo-de-design.md
  mkdocs.yml
Labels: release, entrega2
