Repository Interacao-Humano-Computador/2022.1-Faculdade-de-Arquitetura-e-Urbanismo, pull requests merged in 2022-09, with the labels that each got.

#72 Planejamento protótipo alta fidelidade
  docs/designAvalEDesenv/nivel3/planej-avaliacao-prototipo-alta-fidelidade.md
  mkdocs.yml
Labels: documentation, entrega7

#77 Correção verif thalisson
  docs/analise-de-requisitos/aspectos-eticos.md
  docs/designAvalEDesenv/nivel1/storyboard/planej-relato-result-storyboard.md
  docs/planejamento/processo-de-design.md
Labels: entrega7

#76 Verif cronograma
  docs/assets/verif-cronograma.png
  docs/verificacao/verif-cronograma.md
Labels: entrega7

#75 Planej prototipo alta fidelidade
  docs/designAvalEDesenv/nivel3/planej-avaliacao-prototipo-alta-fidelidade.md
Labels: documentation, entrega7

#78 Relat result prot alta fidelidade
  docs/designAvalEDesenv/nivel3/entrevista.md
  docs/designAvalEDesenv/nivel3/relato-result-protot-alta.md
  docs/designAvalEDesenv/nivel3/teste_piloto.md
  mkdocs.yml
Labels: entrega7

#71 Resultado de prototipo alta fidelidade
  docs/designAvalEDesenv/nivel3/planej-relato-result-protot-alta.md
Labels: entrega7

#74 Relato dos resultados protótipo papel
  docs/assets/logo youtube.png
  docs/designAvalEDesenv/nivel2/prototPapel/entrevistas.md
  docs/designAvalEDesenv/nivel2/prototPapel/planej-relato-result-prot-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/relato-result-prot-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/teste-piloto.md
  docs/planejamento/metodologia-e-processos.md
  mkdocs.yml
Labels: documentation, entrega7

#80 Aba para protótipo papel
  docs/analise-de-requisitos/metas-de-usabilidade.md
  docs/analise-de-requisitos/personas.md
  docs/designAvalEDesenv/nivel2/prototPapel/entrevistas.md
  docs/designAvalEDesenv/nivel2/prototPapel/planej-avaliacao-prototipo-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/planej-relato-result-prot-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/prototipo-de-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/relato-result-prot-papel.md
  docs/verificacao/planejamento-geral.md
  docs/verificacao/verif-prot-papel.md
  mkdocs.yml
Labels: enhancement, entrega7

#81 Development into main
  docs/analise-de-requisitos/aspectos-eticos.md
  docs/analise-de-requisitos/metas-de-usabilidade.md
  docs/analise-de-requisitos/personas.md
  docs/assets/logo youtube.png
  docs/assets/verif-cronograma.png
  docs/designAvalEDesenv/nivel1/storyboard/planej-relato-result-storyboard.md
  docs/designAvalEDesenv/nivel2/prototPapel/entrevistas.md
  docs/designAvalEDesenv/nivel2/prototPapel/planej-avaliacao-prototipo-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/planej-relato-result-prot-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/prototipo-de-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/relato-result-prot-papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/relato_papel.md
  docs/designAvalEDesenv/nivel2/prototPapel/teste-piloto.md
  docs/designAvalEDesenv/nivel3/entrevista.md
  docs/designAvalEDesenv/nivel3/planej-avaliacao-prototipo-alta-fidelidade.md
  docs/designAvalEDesenv/nivel3/planej-relato-result-protot-alta.md
  docs/designAvalEDesenv/nivel3/prototipo-alta-fidelid.md
  docs/designAvalEDesenv/nivel3/relato-result-protot-alta.md
  docs/designAvalEDesenv/nivel3/teste_piloto.md
  docs/planejamento/cronograma-de-atividades.md
  docs/planejamento/metodologia-e-processos.md
  docs/planejamento/processo-de-design.md
  docs/verificacao/planejamento-geral.md
  docs/verificacao/verif-aspec-eticos.md
  docs/verificacao/verif-cronograma.md
  docs/verificacao/verif-guia-estilo.md
  docs/verificacao/verif-metodologia.md
  docs/verificacao/verif-pa-analise-tarefas.md
  docs/verificacao/verif-pa-storyboard.md
  docs/verificacao/verif-perf-usuario.md
  docs/verificacao/verif-personas.md
  docs/verificacao/verif-pr-prot-papel.md
  docs/verificacao/verif-pr-storyboard.md
  docs/verificacao/verif-proces-design.md
  docs/verificacao/verif-prot-papel.md
  docs/verificacao/verif-rel-storyboard.md
  docs/verificacao/verif-storyboard.md
  mkdocs.yml
Labels: release, entrega7
