Repository Interacao-Humano-Computador/2022.1-Faculdade-de-Arquitetura-e-Urbanismo, pull requests merged in 2022-08, with the labels that each got.

#29 Princípios gerais do projeto
  docs/analise-de-requisitos/principios-gerais.md
  mkdocs.yml
Labels: entrega3

#32 Metas de usabilidade
  docs/analise-de-requisitos/metas-de-usabilidade.md
  mkdocs.yml
Labels: entrega3

#37 (#36) planejamento do storyboard
  docs/designAvalEDesenv/storyboard/planejamento-da-avaliacao-do-storyboard.md
Labels: entrega4

#38 Planejamento da Analise Tarefas
  docs/designAvalEDesenv/analiseTarefas/planejamento-analise-tarefas.md
Labels: entrega4

#40 Planejamento relato dos resultados aht
  docs/designAvalEDesenv/analiseTarefas/planej-relato-result-analise-tarefas.md
Labels: entrega4

#41 Planejamento de relato dos resultados do Storyboard
  docs/designAvalEDesenv/storyboard/planej-relato-result-storyboard.md
Labels: entrega4

#43 Development into main
  docs/analise-de-requisitos/Perfil-de-usuario.md
  docs/analise-de-requisitos/analise-de-tarefas.md
  docs/analise-de-requisitos/guia-de-estilo.md
  docs/analise-de-requisitos/metas-de-usabilidade.md
  docs/analise-de-requisitos/personas.md
  docs/apresentacoes.md
  docs/designAvalEDesenv/analiseTarefas/planej-relato-result-analise-tarefas.md
  docs/designAvalEDesenv/analiseTarefas/planejamento-analise-tarefas.md
  docs/designAvalEDesenv/storyboard/planej-relato-result-storyboard.md
  docs/designAvalEDesenv/storyboard/planejamento-da-avaliacao-do-storyboard.md
  docs/planejamento/cronograma-de-atividades.md
  mkdocs.yml
Labels: release, entrega4

#48 Correção do guia de estilo
  docs/analise-de-requisitos/guia-de-estilo.md
Labels: entrega5

#55 Resultado análise tarefas
  docs/designAvalEDesenv/analiseTarefas/entrevistas.md
  docs/designAvalEDesenv/analiseTarefas/planejamento-analise-tarefas.md
  docs/designAvalEDesenv/analiseTarefas/relato-result-analise-tarefas.md
  mkdocs.yml
Labels: entrega5

#56 Development
  docs/analise-de-requisitos/analise-de-tarefas.md
  docs/analise-de-requisitos/guia-de-estilo.md
  docs/apresentacoes.md
  docs/assets/figura2.png
  docs/designAvalEDesenv/analiseTarefas/entrevistas.md
  docs/designAvalEDesenv/analiseTarefas/planejamento-analise-tarefas.md
  docs/designAvalEDesenv/analiseTarefas/relato-result-analise-tarefas.md
  docs/designAvalEDesenv/prototPapel/planej-avaliacao-prototipo-papel.md
  docs/designAvalEDesenv/prototPapel/relato_papel.md
  docs/designAvalEDesenv/storyboard/relato-da-avaliação-do-storyboard.md
  docs/designAvalEDesenv/storyboard/storyboard.md
  docs/planejamento/cronograma-de-atividades.md
  mkdocs.yml
Labels: release, entrega5

#64 Verif matheus
  docs/designAvalEDesenv/nivel1/storyboard/storyboard.md
  docs/verificacao/planejamento-geral.md
  docs/verificacao/verif-analise-tarefas.md
  docs/verificacao/verif-metas.md
  docs/verificacao/verif-pa-prot-papel.md
  docs/verificacao/verif-pr-analise-tarefas.md
  mkdocs.yml
Labels: entrega6

#63 Verif caio
  docs/apresentacoes.md
  docs/assets/100porcem.png
  docs/assets/Captura de tela 2022-08-22 224349.png
  docs/verificacao/verif-aspec-eticos.md
  docs/verificacao/verif-pr-storyboard.md
  docs/verificacao/verif-proces-design.md
  docs/verificacao/verif-prot-papel.md
Labels: entrega6

#57 Prototipo de papel
  docs/assets/figma-logo.png
  docs/designAvalEDesenv/nivel2/prototPapel/planej-avaliacao-prototipo-papel.md
  docs/planejamento/metodologia-e-processos.md
Labels: entrega6

#61 Verif thalisson
  docs/assets/verif-pa-analise-tarefas.jpg
  docs/assets/verif-pa-storyboard.png
  docs/assets/verif-rel-storyboard.png
  docs/verificacao/verif-pa-analise-tarefas.md
  docs/verificacao/verif-pa-storyboard.md
  docs/verificacao/verif-rel-storyboard.md
Labels: entrega6

#62 Verif mateus franco
  docs/assets/figura-2-relato-resultados-aht.png
  docs/assets/figura-3-sites-avaliados.png
  docs/assets/figura-4-site-escolhido.png
  docs/assets/figura1-principios-gerais.png
  docs/verificacao/verif-princ-gerais.md
  docs/verificacao/verif-rel-analise-tarefas.md
  docs/verificacao/verif-site-escolhido.md
  docs/verificacao/verif-sites-aval.md
Labels: entrega6
